# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20161225_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='unlockedBy',
            field=models.ManyToManyField(blank=True, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='hints',
            name='usedBy',
            field=models.ManyToManyField(blank=True, to='team.Team'),
        ),
    ]
