# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20161225_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hints',
            new_name='Hint',
        ),
        migrations.RenameModel(
            old_name='WrongSubmissions',
            new_name='WrongSubmisson',
        ),
    ]
