# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challengefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengefile',
            name='fileName',
            field=models.CharField(default='pe', max_length=255),
            preserve_default=False,
        ),
    ]
